### ISSUE TITLE
[BUG]: User can interact with holes even when the game is not running

### ISSUE THREAD

**Issue by dexterousdhruv** [naikmubashir/FeF-WhackAMole#13]
## Description
Currently, the users are able to interact with the mole holes even when the game is in a non-active state (i.e., when the game is not running or after the timer has expired). This allows users to click on the holes and possibly trigger interactions, which is unintended behavior.

## Demo
https://github.com/user-attachments/assets/5f6600fd-f725-4458-afba-1a1bb6b9db6f

## Steps to Reproduce
- Open the Whack-a-Mole game.
- Attempt to click on any of the mole holes.
- Observe that the holes still responds to user clicks, even when the game isn't running.

## Expected Behavior
- The user should only be able to interact with the mole holes when the game is actively running.
- After the game ends, the mole holes should be unresponsive to user clicks, and no points or game interactions should occur.
- The holes should only become clickable again when the game restarts.

**Comment by naikmubashir** [comment]
Thanks for raising this issue!

**Comment by dexterousdhruv** [comment]
Hey @naikmubashir! I'd like to work on this one since no one took it up. Assign it to me

**Comment by dexterousdhruv** [comment]
@naikmubashir Have a look.
