### ISSUE TITLE
 Add countdown timer to show when the game is ending 

### ISSUE THREAD

**Issue by naikmubashir** [naikmubashir/FeF-WhackAMole#3]
### Feature Request

We need to add a countdown timer that displays the remaining time for the game. This will help players know how much time they have left to play, enhancing the overall gaming experience.

**Tasks:**
- Implement a countdown timer in the game interface.
- Ensure the timer starts at the beginning of the game and ends when the game is over.
- Display the remaining time prominently on the screen.

**NOTE:**
- Make sure the UI of the web app doesn't change.
- Ensure that the moles are fully visible when they come out.

**Comment by Master9090rgb** [comment]
I would like to work on this issue.I have good experience working with c++,python but i m new to open source contribution if you can help me understand how to contribute to this issue i will try to resolve the issue.
Thank You.

**Comment by Master9090rgb** [comment]
I would like to work on this issue can you plz assign it to me.I have good experience working with c++,python,javascript,css,html but i m new to open source contribution if you assign it to me i will try to resolve the issue.
Thank You.

**Comment by uskYash** [comment]
Hi , I hope you're doing well. I I believe I can contribute effectively, and I'm eager to help resolve it. If it's possible, could you please assign me this task? I would really appreciate the opportunity. Thank you!"

**Comment by dexterousdhruv** [comment]
Could you please assign me this issue? I would like to work on it.

**Comment by qbinh1423** [comment]
Hello! I am a programming student and would like to try this issue to contribute and improve my skills. Can I try this? Thank you!

**Comment by naikmubashir** [comment]
@qbinh1423 @dexterousdhruv  @Master9090rgb @uskYash Make sure you star the repository, I'll be adding more such beginner friendly issues featuring **hacktobesfest**

**Comment by naikmubashir** [comment]
You can open a pull request for this issue, but make sure it doesn't change the UI of the game. **The Mole should be fully visible when it comes out**

**Comment by dexterousdhruv** [comment]
@naikmubashir Kindly review the PR.
