### ISSUE TITLE
[Feature] Add Penalty for Misses

### ISSUE THREAD

**Issue by naikmubashir** [naikmubashir/FeF-WhackAMole#7]
Introduce a penalty system for missed mole clicks to make the game more challenging.

**Details:**

- If the player clicks on an empty hole (where there is no mole), they lose points (e.g., -1 point per miss).
- Display a "Missed!" animation or sound effect when a miss occurs to notify the player of the mistake.

**Expected Outcome:**

- Players are penalized for inaccurate clicks, encouraging precision and making the game more engaging.

**Comment by Telomelonia** [comment]
@naikmubashir 
Plz, review the PR

**Comment by naikmubashir** [comment]
This issue has been addressed in PR #8  and will be closed now.
