### ISSUE TITLE
Add Game Rules 

### ISSUE THREAD

**Issue by naikmubashir** [naikmubashir/FeF-WhackAMole#9]
**Feature Request:**

Implement a clear set of game rules that players can easily access before starting the game.

**Details:**

- Create a dedicated section for the rules on the main game page or as a popup/modal.
- Include the following rules:
  - How to play (e.g., click on the moles to score points).
  - Scoring system (e.g., points per mole, penalties for misses).
  - Time limits (eg, one gameplay is of 30seconds)
### IMPORTANT NOTE: Make sure the UI of the game isn't affect . Check for all the dimensions (mobile size, tablet size)

**Expected Outcome:**

- Players will have a better understanding of the game mechanics, leading to improved gameplay experience.

**Benefits:**

- Enhances user experience by providing clarity on game objectives.
- Reduces confusion and improves player engagement.

**Comment by dexterousdhruv** [comment]
@naikmubashir  I am on it.

**Comment by dexterousdhruv** [comment]
Tentative Design: The modal appears as an overlay over the main game page.

> ![{B75DF757-973D-407E-9173-44C695A2CB2A}](https://github.com/user-attachments/assets/f8a85dc1-9e22-4b72-9e61-f08add20f228)

Suggest changes, if any.

**Comment by naikmubashir** [comment]
- I would like to know if this disappears if we click anywhere outside.
- Make sure this is responsive.
@dexterousdhruv

**Comment by dexterousdhruv** [comment]
Yes, it is responsive and disappears, when clicked on close btn as well as anywhere outside.
Here's the demo: 

https://github.com/user-attachments/assets/0a2fed95-c45a-4089-9878-92772cf8c9ac

**Comment by naikmubashir** [comment]
One last thing , we shouldn't be able to start the game while rules are displaying.

**Comment by dexterousdhruv** [comment]
Since the modal is overlay, the user anyway can't start the game while rules are displayed. But to be error free, I will still disable the start button.

However, I feel that the reverse should also be there, i.e, the user isn't able to display rules, while the game is being played. What do you say ?

**Comment by naikmubashir** [comment]
Good point! I agree with your suggestion. Implement both the restrictions and open a pr.
